-- Generated by Oracle SQL Developer Data Modeler 21.1.0.092.1221
--   at:        2021-05-29 16:53:57 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE access_point CASCADE CONSTRAINTS;

DROP TABLE access_point_bridge CASCADE CONSTRAINTS;

DROP TABLE devices CASCADE CONSTRAINTS;

DROP TABLE router CASCADE CONSTRAINTS;

DROP TABLE server CASCADE CONSTRAINTS;

DROP TABLE switch CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE access_point (
    mac          VARCHAR2(45 CHAR) NOT NULL,
    ap_essid     INTEGER,
    device_type  VARCHAR2(45)
);

ALTER TABLE access_point ADD CONSTRAINT access_point_pk PRIMARY KEY ( mac );

CREATE TABLE access_point_bridge (
    essid  VARCHAR2(45 CHAR) NOT NULL,
    bssid  VARCHAR2(45) NOT NULL
);

ALTER TABLE access_point_bridge ADD CONSTRAINT access_point_bridge_pk PRIMARY KEY ( essid );

ALTER TABLE access_point_bridge ADD CONSTRAINT access_point_bridge_bssid_un UNIQUE ( bssid );

CREATE TABLE devices (
    mac          VARCHAR2(45 CHAR) NOT NULL,
    ip           VARCHAR2(45 CHAR) NOT NULL,
    device_type  VARCHAR2(105 CHAR) NOT NULL,
    os           VARCHAR2(105 CHAR) NOT NULL
);

ALTER TABLE devices ADD CONSTRAINT devices_pk PRIMARY KEY ( mac );

ALTER TABLE devices ADD CONSTRAINT devices_ip_un UNIQUE ( ip );

CREATE TABLE router (
    ip_int_1    VARCHAR2(45 CHAR) NOT NULL,
    ip_int_2    VARCHAR2(45 CHAR) NOT NULL,
    ip_int_3    VARCHAR2(45 CHAR) NOT NULL,
    ip_int_4    VARCHAR2(45 CHAR) NOT NULL,
    switch_mac  VARCHAR2(45 CHAR) NOT NULL
);

ALTER TABLE router ADD CONSTRAINT router_pk PRIMARY KEY ( switch_mac );

ALTER TABLE router ADD CONSTRAINT router_ip_int_1_un UNIQUE ( ip_int_1 );

ALTER TABLE router ADD CONSTRAINT router_ip_int_2_un UNIQUE ( ip_int_2 );

ALTER TABLE router ADD CONSTRAINT router_ip_int_3_un UNIQUE ( ip_int_3 );

ALTER TABLE router ADD CONSTRAINT router_ip_int_4_un UNIQUE ( ip_int_4 );

ALTER TABLE router ADD CONSTRAINT router_mac_un UNIQUE ( switch_mac );

CREATE TABLE server (
    ip           VARCHAR2(45 CHAR) NOT NULL,
    server_type  VARCHAR2(45 CHAR) NOT NULL,
    os           VARCHAR2(45 CHAR) NOT NULL,
    switch_mac   VARCHAR2(45 CHAR) NOT NULL
);

ALTER TABLE server ADD CONSTRAINT server_pk PRIMARY KEY ( ip );

ALTER TABLE server ADD CONSTRAINT server_mac_un UNIQUE ( switch_mac );

CREATE TABLE switch (
    port_id      INTEGER NOT NULL,
    mac          VARCHAR2(45 CHAR) NOT NULL,
    vlan         INTEGER NOT NULL,
    device_type  VARCHAR2(45 CHAR) NOT NULL
);

ALTER TABLE switch ADD CONSTRAINT switch_pk PRIMARY KEY ( port_id );

ALTER TABLE switch ADD CONSTRAINT switch_mac_un UNIQUE ( mac );

ALTER TABLE router
    ADD CONSTRAINT router_switch_fk FOREIGN KEY ( switch_mac )
        REFERENCES switch ( mac );

ALTER TABLE server
    ADD CONSTRAINT server_switch_fk FOREIGN KEY ( switch_mac )
        REFERENCES switch ( mac );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
